In [2]:
#we cant perform methematical functions directly in List 
#we can perforn methematical functions directly in Array.
#We use array in numpy
#muti type arrays are here.

In [16]:
l = [10,20,30,40,50]
print(l)
print(type(l))

l = [[10,20],[40,50,60]]
l
print(l*2)

[10, 20, 30, 40, 50]
<class 'list'>
[[10, 20], [40, 50, 60], [10, 20], [40, 50, 60]]


In [34]:
#array:
import numpy as np
l = np.array([[10,20,30],[40,50,60]])
print(l)
print(l*2)
l[1]

[[10 20 30]
 [40 50 60]]
[[ 20  40  60]
 [ 80 100 120]]


array([40, 50, 60])

In [40]:
# Single Array :
a = np.array([10,20,30,40,50])
print("Single Array  ============> ",a,type(a))

Single Array  ============>  [10 20 30 40 50] <class 'numpy.ndarray'>


In [48]:
# Multi Array:
m = np.array([[10,20,30,],[40,50,60],[70,80,90]])
print('Multi dimensions Array =========>')
print(m,type(m))

Multi dimensions Array =========>
[[10 20 30]
 [40 50 60]
 [70 80 90]] <class 'numpy.ndarray'>


In [60]:
e = np.array([[10,20,30],[40,50,60]])
print(e)

[[10 20 30]
 [40 50 60]]


In [100]:
# Slicing : 
a = np.array([10,20,30,40,50,60,70,80])
print(a[0:1])
print(a[2:4])
print(a[4:8])
print(a[-5:-2])
print(a[5])
print(a[-3:-2])

[10]
[30 40]
[50 60 70 80]
[40 50 60]
60
[60]


In [350]:
m = np.array([[10,20,30,],[40,50,60],[70,80,90]])
#print(m)

import numpy as np
arra2d = np.arange(25).reshape(5,5)
arra2d


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [361]:
arra2d[2,2] 

np.int64(12)

In [365]:
arra2d[4,4]

np.int64(24)

In [367]:
arr3d = np.arange(64).reshape(2,4,8)
arr3d

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]])

In [375]:
arr3d[0,3,7],arr3d[1,3,7]

(np.int64(31), np.int64(63))

In [410]:
arr2 = np.arange(50).reshape(5,10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [436]:
arr2[2:3,1:5]

array([[21, 22, 23, 24]])

In [438]:
arr2[0:4,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [440]:
arr2[1:4,3:6]

array([[13, 14, 15],
       [23, 24, 25],
       [33, 34, 35]])

In [442]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [448]:
arr2[0:5,0:1]

array([[ 0],
       [10],
       [20],
       [30],
       [40]])

In [480]:
a = arr2[0:5,3:4] 
for i in a:
    if i<40:
        print(i)

[3]
[13]
[23]
[33]


In [488]:
arr2[4:5,0:10]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [174]:
import random
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0:1])
print(arr[0:3,1:4])
print(arr[0:2,1:2])
print(arr[0][3],arr[1][3])

[[10 20 30 40]]
[[20 30 40]
 [60 70 80]]
[[20]
 [60]]
40 80


In [268]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.any(1))
print(arr.argmin(0))
print(arr.argsort(1))
print(arr.dtype)

(2, 4)
8
2
[ True  True]
[0 0 0 0]
[[0 1 2 3]
 [0 1 2 3]]
int64


In [520]:
a = np.arange(20).reshape(4,5)
b = np.arange(20).reshape(4,5)
print(a),print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


(None, None)

# Mathematiacal operation and functions:

In [535]:
print(a+b)
print(np.add(a,b))


[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]


In [527]:
print(a-b)
print(np.subtract(a,b))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [537]:
print(a*b)
print(np.multiply(a,b))

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]]
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]]


In [539]:
print(a/b)
print(np.divide(a,b))

[[nan  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[nan  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


C:\Users\ADMIN\AppData\Local\Temp\ipykernel_13208\1114211024.py:1: RuntimeWarning: invalid value encountered in divide
  print(a/b)
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_13208\1114211024.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.divide(a,b))


In [547]:
print(a**2)
print(np.power(a,2))

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]]
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]]


In [563]:
print(a%20)
print(np.mod(a,20))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


# join and split:

In [566]:
#concatinate :

a = np.arange(10)
b = np.arange(10)

In [570]:
print(np.concatenate([a,b]))

[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]


In [572]:
import numpy as np

In [586]:
a = np.array([10,20,30,40])
b = np.array([50,60,70,80])

print(np.concatenate([a,b]))

#Axis ==== 0,1
print(np.concatenate([a,b],axis=0)) #--------> axis=0 means verticle.
#print(np.concatenate([a,b],axis=1))  #--------> axis=1 not working on one dimension.


[10 20 30 40 50 60 70 80]
[10 20 30 40 50 60 70 80]


In [594]:
a = np.array([[10,20,30,40],[50,60,70,80]])
b = np.array([[1,2,3,4],[5,6,7,8]])

print(np.concatenate([a,b],axis=0))
print(np.concatenate([a,b],axis=1))

[[10 20 30 40]
 [50 60 70 80]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[10 20 30 40  1  2  3  4]
 [50 60 70 80  5  6  7  8]]


In [598]:
print(np.hstack([a,b]))  #working as horizontal axis = 1

[[10 20 30 40  1  2  3  4]
 [50 60 70 80  5  6  7  8]]


In [602]:
print(np.vstack([a,b])) #Working as verticle axis = 0

[[10 20 30 40]
 [50 60 70 80]
 [ 1  2  3  4]
 [ 5  6  7  8]]


# Split Array:

In [635]:
import random
arr = np.array([[10,20,30,40,50,60],[70,80,90,100,110,120]])
arr

array([[ 10,  20,  30,  40,  50,  60],
       [ 70,  80,  90, 100, 110, 120]])

In [643]:
print(np.split(arr,2))

[array([[10, 20, 30, 40, 50, 60]]), array([[ 70,  80,  90, 100, 110, 120]])]


In [681]:
b = np.array_split(arr,3)
b

[array([[10, 20, 30, 40, 50, 60]]),
 array([[ 70,  80,  90, 100, 110, 120]]),
 array([], shape=(0, 6), dtype=int64)]

# Append , Removing , inserting : 

In [701]:
#Adding :
a = [10,20,30,40,50,60]
b = np.append(a,[70,80,90])
print(b)

[10 20 30 40 50 60 70 80 90]


In [719]:
# This Wil Convert The Array Into one dimension the append the value into it
arr = np.array([[10,20,30,40,50,60],[70,80,90,100,110,120]])  
b = np.append(arr,[10,20,30])
print(b)
print(b.reshape(3,5))

[ 10  20  30  40  50  60  70  80  90 100 110 120  10  20  30]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120  10  20  30]]


In [757]:
# Inserting :
a = [10,20,30,40,50,60]

b = np.insert(a,[0],[100,200,300])
print(b)


[100 200 300  10  20  30  40  50  60]


In [825]:
arr = np.array([[10,20,30,40,50,60],[70,80,90,100,110,120]])  
b = np.insert(arr,[1],[200],axis=0)
c = np.insert(arr,[0],[200],axis=1)
print(b)
print(c)

[[ 10  20  30  40  50  60]
 [200 200 200 200 200 200]
 [ 70  80  90 100 110 120]]
[[200  10  20  30  40  50  60]
 [200  70  80  90 100 110 120]]


In [873]:
# Delete:
arr = np.array([[10,20,30,40,50,60],[70,80,90,100,110,120]])  
a = np.delete(arr,2)
b = np.delete(arr,[0],axis=0) 
c = np.delete(arr,[1,4],axis=1)
print(a)
print(b)
print(c)

[ 10  20  40  50  60  70  80  90 100 110 120]
[[ 70  80  90 100 110 120]]
[[ 10  30  40  60]
 [ 70  90 100 120]]


# Sort,search,filter ;

In [890]:
# Search :
a = np.array([60,50,40,300,20,10])
print(a)
print(np.sort(a))

[ 60  50  40 300  20  10]
[ 10  20  40  50  60 300]


In [892]:
arr = np.array([[100,200,30,400,50,60],[70,800,900,100,110,120]])  
print(arr)
print(np.sort(arr))

[[100 200  30 400  50  60]
 [ 70 800 900 100 110 120]]
[[ 30  50  60 100 200 400]
 [ 70 100 110 120 800 900]]


In [924]:
#Search :
a = np.array([60,50,40,300,20,10])
c = np.where(a == 20 )
print(c)

(array([4]),)


In [968]:
import numpy as np
a = np.array([10,20,30,40,50])
b = np.searchsorted(a,10)
print(b)

0


# Filtering:

In [971]:
a = np.array([10,20,30,40,50,60])
b = [False,True,True,False,True,False]
new = a[b]
print(new)

[20 30 50]


In [983]:
a = np.array([10,20,30,40,50,51])
b = a%2==0
print(a[b])
print(b)

[10 20 30 40 50]
[ True  True  True  True  True False]


In [987]:
a = np.array([10,20,30,40,50,60])
b = a>20
print(b)
print(a[b])

[False False  True  True  True  True]
[30 40 50 60]


# Aggregation Function:

In [1003]:
a = np.array([10,20,30,40,50,60,0])

print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.count_nonzero(a))
print(np.size(a))
print(np.cumsum(a))
print(np.cumprod(a))

0
60
30.0
6
7
[ 10  30  60 100 150 210 210]
[       10       200      6000    240000  12000000 720000000         0]


In [1020]:
#Example:
price = np.array([100,120,130,150,180,200])
quantity = np.array([10,5,40,20,30,70])

print(price,'\n',quantity)
pro = np.cumprod([price,quantity],axis=0)
print(np.cumsum(pro[1]))
print(pro[1].sum())

[100 120 130 150 180 200] 
 [10  5 40 20 30 70]
[ 1000  1600  6800  9800 15200 29200]
29200
